config/routes.rb
Glenmark::Application.routes.draw do

  resources :cvns

  resources :useful_links

  resources :downloads

  get "welcome/index"
  get 'about_us' => "welcome#about_us", :as => :about_us
  get 'terms_of_use' => "welcome#terms_of_use", :as => :terms_of_use
  get 'membership_benefits' => "welcome#membership_benefits", :as => :membership_benefits
  get 'disclaimer' => "welcome#disclaimer", :as => :disclaimer
  get 'drug_info_search' => "drug_infos#search", :as => :drug_info_search

  resources :events

  resources :pages

  resources :updates

  resources :conference_calendars

  resources :trials

  resources :drug_infos

  resources :banners

  devise_for :users do 
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
 
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :webcasts
  root :to => "welcome#index"

end

app/models/download.rb
class Download < ActiveRecord::Base
  has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  paginates_per 2
end

app/controllers/downloads_controller.rb
class DownloadsController < InheritedResources::Base
  before_filter :authenticate_user!
def index
@iraas_journal = Download.where("download_type = 'iRaas Journal'").order("created_at desc").page params[:page]
@telma = Download.where("download_type = 'Telma 24 X 7'").order("created_at desc").page params[:page]
@slide_kits = Download.where("download_type = 'Slide Kits'").order("created_at desc").page params[:page]
@pem = Download.where("download_type = 'Patient Education Material'").order("created_at desc").page params[:page]
@guideline = Download.where("download_type = 'Guidelines'").order("created_at desc").page params[:page]
@vg = Download.where("download_type = 'Video Gallery'").order("created_at desc").page params[:page]
@gaa = Download.where("download_type = 'Guideline - Antcoagulant Antiplatelet'").order("created_at desc").page params[:page]
@ga = Download.where("download_type = 'Guideline - Arrythmias'").order("created_at desc").page params[:page]
@gchd = Download.where("download_type = 'Guideline - Coronary Heart Disease'").order("created_at desc").page params[:page]
@gci = Download.where("download_type = 'Guideline - Coronary Intervantions'").order("created_at desc").page params[:page]
@gd = Download.where("download_type = 'Guideline - Diabetes'").order("created_at desc").page params[:page]
@ghdw = Download.where("download_type = 'Guideline - Heart Disease & Women'").order("created_at desc").page params[:page]
@ghf = Download.where("download_type = 'Guideline - Hypertension'").order("created_at desc").page params[:page]
end 
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/views/downloads/_form.html.erb
<%= form_for(@download, :html => { :multipart => true }) do |f| %>
  <% if @download.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@download.errors.count, "error") %> prohibited this download from being saved:</h2>

      <ul>
      <% @download.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :download_type %><br />
 <%= select :download, :download_type, ['iRAAS Journal', 'Telma 24 X 7', 'Slide Kits', 'Patient Education Material'] %>

  </div>
  <div class="field">
  <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/downloads/edit.html.erb
<h1>Editing download</h1>

<%= render 'form' %>

<%= link_to 'Show', @download %> |
<%= link_to 'Back', downloads_path %>

app/views/downloads/index.html.erb
<h1>Downloads</h1>

<h2>Telma 24 X 7</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @telma.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @telma %>
<br />

<h2>iRaas Journal</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @iraas_journal.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @iraas_journal %>
<br />
<h2>Guidelines</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @guideline.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @guideline %>
<br />

<h2>Guideline - Antcoagulant Antiplatelet</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @gaa.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @gaa %>
<br />

<h2>Guideline - Arrythmias</h2>

<table>
  <tr> 
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @ga.each do |download| %>
  <tr> 
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @ga %>
<br />

<h2>Guideline - Coronary Heart Disease</h2>

<table>
  <tr> 
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @gchd.each do |download| %>
  <tr> 
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @gchd %>
<br />

<h2>Guideline Coronary Intervantions</h2>

<table>
  <tr> 
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @gci.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>  
<% end %>
</table>
<%= paginate @gci %>
<br />

<h2>Guideline - Diabetes</h2>

<table>
  <tr> 
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @gd.each do |download| %>
  <tr>  
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr> 
<% end %>
</table>
<%= paginate @gd %>
<br />  

<h2>Guideline - Heart Disease & Women</h2>

<table>
  <tr> 
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @ghdw.each do |download| %>
  <tr>  
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr> 
<% end %>
</table>
<%= paginate @ghdw %>
<br />  

<h2>Guideline - Hypertension</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @ghf.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description.html_safe %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @ghf %>
<br />


<h2>Slide Kits</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @slide_kits.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @slide_kits %>
<br />

<h2>Patient Education Material</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @pem.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @pem %>

<br />

<h2>Video Gallery</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @vg.each do |download| %>
  <tr>
<td><%= link_to download.title, download.attachment.url  %></td>
    <td><%= download.description %></td>
    <td><%= link_to 'Show', download %></td>
  </tr>
<% end %>
</table>
<%= paginate @pem %>

<br />

app/views/downloads/new.html.erb
<h1>New download</h1>

<%= render 'form' %>

<%= link_to 'Back', downloads_path %>

app/views/downloads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%=  @download.title  %>

</p>

<p>
  <b>Description:</b>
  <%= @download.description.html_safe %>
</p>

<p>
<%= link_to "Download", @download.attachment.url  %>

</p>
<%= link_to 'Back', downloads_path %>