config/routes.rb
Glenmark::Application.routes.draw do

  resources :cvns

  resources :useful_links

  resources :downloads

  get "welcome/index"
  get 'about_us' => "welcome#about_us", :as => :about_us
  get 'terms_of_use' => "welcome#terms_of_use", :as => :terms_of_use
  get 'membership_benefits' => "welcome#membership_benefits", :as => :membership_benefits
  get 'disclaimer' => "welcome#disclaimer", :as => :disclaimer
  get 'drug_info_search' => "drug_infos#search", :as => :drug_info_search

  resources :events

  resources :pages

  resources :updates

  resources :conference_calendars

  resources :trials

  resources :drug_infos

  resources :banners

  devise_for :users do 
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
 
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :webcasts
  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
         can :read, :all
      # cannot [ :update, :delete ], :all
      
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_ability.rb
# All back end users (i.e. Active Admin users) are authorized using this class
class AdminAbility
  include CanCan::Ability

  def initialize(user)
    user ||= AdminUser.new

    # We operate with three role levels:
    # - Editor
    # - Moderator
    # - Manager

    # An editor can to the following:
    can :manage, :all
    end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  has_attached_file :banner, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/cvn.rb
class Cvn < ActiveRecord::Base
  has_attached_file :attachment, :path => ':rails_root/public/system/attachments/:id/:style/:filename.:extension', :styles => { :thumb => "100x100>" }
  paginates_per 5
end

app/models/download.rb
class Download < ActiveRecord::Base
  has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  paginates_per 2
end

app/models/drug_info.rb
class DrugInfo < ActiveRecord::Base
attr_accessor :delete_attachment
before_validation { attachment_drug.clear if delete_attachment == '1' }

  has_attached_file :attachment_drug, :styles => { :thumb => "100x100>" }
   paginate_alphabetically :by => :title
     paginates_per 5
define_index do
    indexes title, :sortable => true
    indexes action

    has created_at, updated_at
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
geocoded_by :location
after_validation :geocode   
  paginates_per 5

end

app/models/page.rb
class Page < ActiveRecord::Base
extend FriendlyId
  friendly_id :title, :use => :slugged
end

app/models/trial.rb
class Trial < ActiveRecord::Base
   attr_accessor :delete_attachment
   before_validation { attachment.clear if delete_attachment == '1' }

  has_attached_file :attachment, :path => ':rails_root/public/system/attachments/:id/:style/:filename.:extension', :styles => { :thumb => "100x100>" } 
  paginates_per 5

  define_index do
   indexes :title
   indexes description
   indexes references
 end

end

app/models/update.rb
class Update < ActiveRecord::Base
  #attr_accessor :attachment_update_file_size, :attachment_update_content_type, :attachment_update_file_name
   attr_accessor :delete_attachment
   before_validation { attachment.clear if delete_attachment == '1' }
  has_attached_file :attachment, :path => ':rails_root/public/system/attachments/:id/:style/:filename.:extension', :styles => { :medium => "300x300>", :thumb => "100x100>" }
  paginates_per 5
end

app/models/useful_link.rb
class UsefulLink < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model

  attr_accessible :email, :password, :password_confirmation, :address,
                  :remember_me, :name, :phone, :specialization, :last_name, 
                  :city, :pincode, :state, :degree, :specify_degree, :specify_institute, :specify_specialization, :approved

  validates :email, :presence => true, :uniqueness => true, :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/ }
  validates :name, :presence => true
  validates :last_name, :presence => true
  validates :address, :presence => true
  validates :city, :presence => true
  validates :pincode, :presence => true
  validates :state , :presence => true
  validates :phone, :presence => true
  validates :specialization, :presence => true
  validates :degree , :presence => true
  validates :specify_institute, :presence => true
  validates :specify_specialization, :presence => true
  validates :specify_degree, :presence => true
  scope :approval_pending, where(:approved => false)  

def active_for_authentication? 
  super && approved? 
end 

def inactive_message 
  if !approved? 
    :not_approved 
  else 
    super # Use whatever other message 
  end 
end
end

app/models/webcast.rb
class Webcast < ActiveRecord::Base


end

app/controllers/updates_controller.rb
class UpdatesController < InheritedResources::Base
  def index
    @updates = Update.order("created_at desc").page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @updates }
    end
  end

end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cvns_helper.rb
module CvnsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :overview %><br />
    <%= f.text_area :overview %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :references %><br />
    <%= f.text_area :references %>
  </div>
 <div class="field">
  <%= f.file_field :attachment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<div id="banner" class="prepend-top"><img src="/images/header_cv_news.jpg" alt="Awaken to health and happiness" /></div>
<div id="content" class="content prepend-top">
<%= render 'form' %>
<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>
</div>

app/views/updates/index.html.erb
<div id="banner" class="prepend-top"><img src="/images/header_cv_news.jpg" alt="Awaken to health and happiness" /></div>
<% @updates.each do |update| %>
	<div id="content" class="note prepend-top">
    <h2><%= update.title %></h2>
    <p><%= update.overview.html_safe %></p>
    <!--
    <td><%= truncate(update.description.html_safe, :length => 200, :separator => 'More') %></td>
    <td><%= update.references %></td>
    -->
    <p><%= link_to 'More...', update %></p>
    </div>
<% end %>
<%= paginate @updates %>

app/views/updates/new.html.erb
<div id="banner" class="prepend-top"><img src="/images/header_cv_news.jpg" alt="Awaken to health and happiness" /></div>
<div id="content" class="content prepend-top">
<%= render 'form' %>
<%= link_to 'Back', updates_path %>
</div>

app/views/updates/show.html.erb
<div id="banner" class="prepend-top"><img src="/images/header_cv_news.jpg" alt="Awaken to health and happiness" /></div>
<div id="content" class="note prepend-top">
	<p id="notice"><%= notice %></p>
	<h2><%= @update.title %></h2>

	<p>
	  <b>Overview:</b>
	  <%= @update.overview.html_safe %>
	</p>

	<p>
	  <b>Description:</b>
	  <%= @update.description.html_safe %>
	</p>
	
	<p>
        <% unless @update.references.blank? || @update.references.nil? %>
	  <b>References:</b>
	  <%= @update.references.html_safe %>
        <% end %>
	</p>
<p>
 <% unless @update.attachment_file_name.nil? %>
<%= link_to @update.attachment_file_name, @update.attachment.url  %>
<% end %>
</p>
	<!-- <%= link_to 'Edit', edit_update_path(@update) %> | -->
	<%= link_to 'Back', updates_path %>
</div>